### ISSUE TITLE
Modify the dir structure of the snitch project

### ISSUE THREAD

**Issue by arjun289** [aviabird/snitch#15]
__Current naming and dir structure__
```
|-- apps
    |-- core
         |-- config 
         |-- lib
             |-- core
                 |-- snitch
                     |-- data
                         |-- schema
                         |-- model
                 |-- tools
                 |-- seed
```
__Suggested naming and dir structure__
```
|-- apps
    |-- snitch
         |-- config 
         |-- lib
             |-- snitch
                 |-- data
                     |-- schema
                     |-- model
                 |-- tools
             |-- seed
```
* The suggested structure will change the name of the application itself.
- [ ] Confirmation needed.

**Comment by oyeb** [comment]
Why keep the nested `snitch`?
```
|-- apps
    |-- snitch
         |-- config 
         |-- lib
         |-- data
             |-- schema
             |-- model
         |-- domain
             |-- quantifier
             |-- ...
         |-- tools
         |-- seed
```

**Comment by pkrawat1** [comment]
main code is always part of lib. We can skip snitch though.
```
|-- apps
    |-- snitch
         |-- config 
         |-- lib
             |-- data
                     |-- schema
                     |-- model
             |-- tools
             |-- seed
```

**Comment by arjun289** [comment]
__Final directory structure as per the discussion__
```
|-- apps
    |-- core
         |-- config 
         |-- lib
             |-- data
                 |-- schema
                 |-- model
             |-- tools
             |-- seed
```

**Comment by arjun289** [comment]
Regarding the name space, now that `snitch` is removed from the structure.
The current name space is 
```
Core.Snitch.Data.Model.LineItem
```
Should it be replaced with 
```
Core.Data.Model.LineItem
```

**Comment by ashish173** [comment]
Can we use `Snitch.Core.Data.Model.LineItem`.

Benefits:-
* Clear namespacing with `Snitch` and in future, we do not get in the way of developers/companies trying to name their services starting with `Core`. A lot of people want to name their sub apps as `Core` as we have seen it.

@aviabird/all Thoughts on this?

**Comment by oyeb** [comment]
I agree with Ashish that our namespaces should be `Snitch.*`, not `Core.Snitch.*`. Here are my sugestions:

**Comment by pkrawat1** [comment]
Snitch should be umbrella project reference here.
```
   apps
       |- Core
              |- Snitch.Core.Support.Factory
              |- Snitch.Core.Schema
       |- Admin
              |- Snitch.Admin.Support.Factory
       |- API
              |- Snitch.API.Support.Factory

```

**Comment by ashish173** [comment]
@arjun289 please implement as per the final suggestions. so that we have some structure for now. If we plan to make any modifications in future that can be done at a later stage.

**Comment by gopalshimpi** [comment]
Its good to have snitch insted of core.snitch.
