### ISSUE TITLE
Improve `User`, add Model and tests

### ISSUE THREAD

**Issue by oyeb** [aviabird/snitch#21]
## `Schema.User`
* [ ] Refactor the changeset functions to match those in ~~`Schema.LineItem`~~ `Schema.Order` (add the `action` argument)
* [ ] Change `@required_fields`, `@password_fields` to `@create_fields` and `@update_fields`
* [ ] Might need migrations:
    - [ ] `:password_hash` should never be null.
    - [ ] Change `naive_datetime` to `utc_datetime`.
    - [ ] ~~Add relation to `Address` (see spree's user schema [here](https://hackmd.io/wS4C6CbkSPS_waUftvci9w#user)). Don't forget to set the `:on_delete` action.~~ Moved to #38.
    - [ ] Remove the `?` from boolean fields (`:is_admin?`).

## `Model.User`
* [ ] This module should have CRUD API, make use of `Snitch.Tools.QueryHelper`

## Tests
* [ ] Schema tests should not use the factory to build/insert `User`. Write assertions on the changeset itself. Cover all error cases.
* [ ] Model tests. No need to test `get` and `get_all`.

## Doctests
* [ ] We could add doctests in Schema or Model to show how the password_hash gets computed.

[Excellent documentation](https://hexdocs.pm/ex_unit/ExUnit.DocTest.html) on how to write doctests. See an example in `Model.LineItem` and `Model.LineItemTest`

## Factory
* [ ] Improve `user_with_address` in `test/support/factory.ex`

**Comment by Euklidian-Space** [comment]
Hello @oyeb.  I would like to contribute to this issue.  I do have some questions.  

1. For the Schema.User you said to add the action argument.  Do you mean an action argument like the one present in Schema.Order ?

2. If the answer to 1 is yes, then do you want Schema.User to be implemented more like Schema.Order?

**Comment by oyeb** [comment]
Thanks for helping us out!
1. You are right, I meant `Schema.Order`, not `LineItem`. And yes, the `action` argument like the one in  `Order` (which gets used by the `QueryHelper` in the `Model.Order`).
2. The goal is to make use of `QueryHelper` in `Model.User`, and `Schema.Order` is just for inspiration :smile:

**Comment by oyeb** [comment]
@Euklidian-Space We just created a [**gitter room**](https://gitter.im/aviabird/snitch) for the repo, feel free to chat with us!

**Comment by Euklidian-Space** [comment]
Hey @oyeb I submitted a PR
