### ISSUE TITLE
Restructure 2.0

### ISSUE THREAD

**Issue by oyeb** [aviabird/snitch#23]
## Approved tasks
We missed a few details in #18 :cry: 

1. According to the [final dir structure](https://github.com/aviabird/snitch/issues/15#issuecomment-369174134), there should be no "`core/`" in `lib/`.
4. `query_helper.ex` is inside `query_helper/`. Let's move it ~~out~~ up.
5. Do we really need the `Data` namespace? We can keep the folder perhaps.
7. Our changeset functions have an `action` argument. It should be the first argument, not the last. The last  an be made a `keyword` if need be.
8. Remove `seed/` from `lib` and place them in `priv/repo/`

## Rejected tasks
1. `__using__` macro in `schema.ex`, `model.ex`, `domain.ex` must self-alias, so that when we do `use Snitch.Data.Schema`, we don't have to _also do_ `alias Snitch.Data.Schema`.
    - > No longer relevant.
3. `use Snitch.Data.Schema` is allowed only in `lib/data/schema/*.ex`, and likewise for `Model` and `Domain`. Everywhere else, they should be aliased.
    - Rationale: We `use` a module to ***become*** like it. For example, all schemas "use" `Ecto.Schema`, because _they are_ schemas.
    - Culprit: `factory.ex`
    - > No longer relevant

## Tasks that moved elsewhere

1. `QueryHelper.update` args should be swapped, struct first and then params.
6. Many `Model` functions have this argument: `id_or_instance`.
    a. Let's rename it to `id_or_struct` (because there's no concept of "instance" in Elixir).
    b. Or consistently accept only `ids` if the function does not load the record from DB, and `<struct_name>` if the function actually operates on the `struct`.

## Dir structure when issue was opened
```sh
$ tree lib
lib
├── core
│   ├── application.ex
│   ├── data
│   │   ├── model
│   │   │   ├── line_item.ex
│   │   │   ├── model.ex
│   │   │   ├── order.ex
│   │   │   └── stock
│   │   │       ├── stock.ex
│   │   │       ├── stock_item.ex
│   │   │       └── stock_location.ex
│   │   └── schema
│   │       ├── address.ex
│   │       ├── country.ex
│   │       ├── line_item.ex
│   │       ├── order.ex
│   │       ├── schema.ex
│   │       ├── state.ex
│   │       ├── stock
│   │       │   ├── stock.ex
│   │       │   ├── stock_item.ex
│   │       │   └── stock_location.ex
│   │       ├── user.ex
│   │       └── variant.ex
│   ├── domain
│   │   ├── domain.ex
│   │   └── stock
│   │       └── inventory.ex
│   ├── repo.ex
│   ├── seed
│   │   └── country_state_seed.ex
│   └── tools
│       └── helpers
│           └── query_helper
│               └── query_helper.ex
└── snitch.ex
```

**Comment by pkrawat1** [comment]
Let's remove `snitch` folder in test too.
current structure is 
`test
