### ISSUE TITLE
Fix those `credo` issues!

### ISSUE THREAD

**Issue by oyeb** [aviabird/snitch#24]
## :scream: :scream: :scream: **56 issues** :scream: :scream: :scream: 
<a href="https://i.imgur.com/QpVR5zJ.png">
  <img src="https://imgur.com/QpVR5zJ.png" />
</a>

## Someone :angel: save us

**Comment by jyotigautam** [comment]
@oyeb What are the type of issues I need to ignore?

**Comment by oyeb** [comment]
**None!**
#22 is blocking work on this, it sets the line max length to 100 columns and hence some of the line length issues will go away. So I guess you could ignore issues where line length is below 100.

**Comment by kartikjagdale** [comment]
@oyeb I understand that this is something important and we need to fix this.
But this looks quite abstract. 
As I see that there are 
`29 code readability issues` and `27 software design suggestions`

I think we can create a sub-issue which targets particular type of issues.
say a separate sub-issue which targets `code readability` and again a separate one for `software design suggestions`
and then we can start with one by one.
@pkrawat1 what you think about this suggestion.
cc: @ashish173

**Comment by oyeb** [comment]
Have you noticed that _all_ software design issues are of the _same type_. If any issue seems abstract, just ask credo to explain it. See `mix credo explain --help`.

**Comment by pkrawat1** [comment]
closed in #28
